site_name: pygcsutils

repo_url: https://github.com/nodd-tools/py-gcs-utils

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.annotate
  markdown_extensions:
    - markdown.extensions.admonition
    - markdown.extensions.codehilite
    - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy

nav:
  - Home: README.md
  - Contributing: CONTRIBUTING.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - Code Reference:
      - Connect: api/connect.md
